// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV72EqIfYQPUklGokc3gbKF0c0z5mGULg',
    appId: '1:479395548206:web:dc867ac3c4d1b26f0d23bf',
    messagingSenderId: '479395548206',
    projectId: 'foodapp-9213e',
    authDomain: 'foodapp-9213e.firebaseapp.com',
    storageBucket: 'foodapp-9213e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQlq7txd3veBxIYU9YvrJx_Yb3XbAmgk',
    appId: '1:479395548206:android:eccf0064c15a02890d23bf',
    messagingSenderId: '479395548206',
    projectId: 'foodapp-9213e',
    storageBucket: 'foodapp-9213e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8MHMmrHZHIyMZv_2gPPKi3gKa3WwQZ_Q',
    appId: '1:479395548206:ios:15ebcfd3c60dc0950d23bf',
    messagingSenderId: '479395548206',
    projectId: 'foodapp-9213e',
    storageBucket: 'foodapp-9213e.appspot.com',
    androidClientId: '479395548206-psoj89hoafcn0g2oemmuc3ogm3ugehni.apps.googleusercontent.com',
    iosClientId: '479395548206-4rpkl1hkd1eh766uj4ph7utp2j5ctmbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelleryApp',
  );
}
